package com.example.goodleslock.utils

object Localization {
    data class LangStrings(
        val uninstalled: String,
        val installed: String,
        val settings: String,
        val searchPlaceholder: String,
        val download: String,
        val open: String,
        val uninstall: String,
        val reinstall: String,
        val languageTitle: String,
        val oneUiVersionTitle: String,
        val detected: String,
        val selectOneUi: String,
        val themeTitle: String,
        val themeDesc: String,
        val warningTitle: String,
        val warningText: String,
        val apply: String,
        val cancel: String,
        val noModules: String
    )

    fun getStrings(lang: String): LangStrings {
        return when (lang) {
            "ru" -> LangStrings(
                uninstalled = "Неустановленные",
                installed = "Установленные",
                settings = "Настройки",
                searchPlaceholder = "Поиск модулей...",
                download = "Скачать",
                open = "Открыть",
                uninstall = "Удалить",
                reinstall = "Переуст.",
                languageTitle = "Язык",
                oneUiVersionTitle = "Версия One UI",
                detected = "Определенная системой",
                selectOneUi = "Выберите One UI",
                themeTitle = "Тема и Стиль",
                themeDesc = "Основной цвет: Фиолетовый (Purple). Шрифт: Roboto.",
                warningTitle = "⚠️ Внимание",
                warningText = "Изменение версии One UI может привести к нестабильной работе или несовместимости модулей. Вы меняете версию на свой страх и риск!",
                apply = "Изменить",
                cancel = "Отмена",
                noModules = "Модули не найдены"
            )
            "uk" -> LangStrings(
                uninstalled = "Не встановлені",
                installed = "Встановлені",
                settings = "Налаштування",
                searchPlaceholder = "Пошук модулів...",
                download = "Завантажити",
                open = "Відкрити",
                uninstall = "Видалити",
                reinstall = "Перевст.",
                languageTitle = "Мова",
                oneUiVersionTitle = "Версія One UI",
                detected = "Визначена системою",
                selectOneUi = "Виберіть One UI",
                themeTitle = "Тема та Стиль",
                themeDesc = "Основний колір: Фіолетовий (Purple). Шрифт: Roboto.",
                warningTitle = "⚠️ Увага",
                warningText = "Зміна версії One UI може призвести до нестабільної роботи або несумісності модулів. Ви змінюєте версію на свій страх і ризик!",
                apply = "Змінити",
                cancel = "Скасувати",
                noModules = "Модулі не знайдені"
            )
            "es" -> LangStrings(
                uninstalled = "No instalados",
                installed = "Instalados",
                settings = "Ajustes",
                searchPlaceholder = "Buscar módulos...",
                download = "Descargar",
                open = "Abrir",
                uninstall = "Desinstalar",
                reinstall = "Reinst.",
                languageTitle = "Idioma",
                oneUiVersionTitle = "Versión de One UI",
                detected = "Detectado por el sistema",
                selectOneUi = "Seleccionar One UI",
                themeTitle = "Tema y Estilo",
                themeDesc = "Color principal: Púrpura. Fuente: Roboto.",
                warningTitle = "⚠️ Advertencia",
                warningText = "Cambiar la versión de One UI puede causar inestabilidad o incompatibilidad de módulos. ¡Hazlo bajo tu propio riesgo!",
                apply = "Aplicar",
                cancel = "Cancelar",
                noModules = "No se encontraron módulos"
            )
            "de" -> LangStrings(
                uninstalled = "Nicht installiert",
                installed = "Installiert",
                settings = "Einstellungen",
                searchPlaceholder = "Module suchen...",
                download = "Herunterladen",
                open = "Öffnen",
                uninstall = "Deinstallieren",
                reinstall = "Neu inst.",
                languageTitle = "Sprache",
                oneUiVersionTitle = "One UI-Version",
                detected = "Vom System erkannt",
                selectOneUi = "One UI auswählen",
                themeTitle = "Thema & Stil",
                themeDesc = "Hauptfarbe: Lila (Purple). Schriftart: Roboto.",
                warningTitle = "⚠️ Achtung",
                warningText = "Das Ändern der One UI-Version kann zu Instabilität oder Inkompatibilität führen. Auf eigene Gefahr!",
                apply = "Anwenden",
                cancel = "Abbrechen",
                noModules = "Keine Module gefunden"
            )
            "zh" -> LangStrings(
                uninstalled = "未安装",
                installed = "已安装",
                settings = "设置",
                searchPlaceholder = "搜索模块...",
                download = "下载",
                open = "打开",
                uninstall = "卸载",
                reinstall = "重新安装",
                languageTitle = "语言",
                oneUiVersionTitle = "One UI 版本",
                detected = "系统检测",
                selectOneUi = "选择 One UI",
                themeTitle = "主题与样式",
                themeDesc = "主色调：紫色 (Purple)。字体：Roboto。",
                warningTitle = "⚠️ 警告",
                warningText = "更改 One UI 版本可能会导致不稳定或模块不兼容。请自行承担风险！",
                apply = "应用",
                cancel = "取消",
                noModules = "未找到模块"
            )
            "fr" -> LangStrings(
                uninstalled = "Non installés",
                installed = "Installés",
                settings = "Paramètres",
                searchPlaceholder = "Rechercher des modules...",
                download = "Télécharger",
                open = "Ouvrir",
                uninstall = "Désinstaller",
                reinstall = "Réinst.",
                languageTitle = "Langue",
                oneUiVersionTitle = "Version One UI",
                detected = "Détecté par le système",
                selectOneUi = "Sélectionner One UI",
                themeTitle = "Thème et Style",
                themeDesc = "Couleur principale : Violet (Purple). Police : Roboto.",
                warningTitle = "⚠️ Attention",
                warningText = "Modifier la version de One UI peut entraîner des instabilités ou des incompatibilités. À vos risques et périls !",
                apply = "Appliquer",
                cancel = "Annuler",
                noModules = "Aucun module trouvé"
            )
            else -> LangStrings( // English (en)
                uninstalled = "Uninstalled",
                installed = "Installed",
                settings = "Settings",
                searchPlaceholder = "Search modules...",
                download = "Download",
                open = "Open",
                uninstall = "Uninstall",
                reinstall = "Reinstall",
                languageTitle = "Language",
                oneUiVersionTitle = "One UI Version",
                detected = "System detected",
                selectOneUi = "Select One UI",
                themeTitle = "Theme & Style",
                themeDesc = "Main color: Purple. Font: Roboto.",
                warningTitle = "⚠️ Warning",
                warningText = "Changing One UI version may lead to unstable operation or module incompatibility. Proceed at your own risk!",
                apply = "Apply",
                cancel = "Cancel",
                noModules = "No modules found"
            )
        }
    }
}
